"""
@file Defines the Pydantic models for data validation and structured output.
"""
from pydantic import BaseModel, Field
from typing import List

class Question(BaseModel):
    """A single, dynamically generated question to be asked to the user."""
    question: str = Field(
        ...,
        description="The exact, user-facing question to be asked, generated by the AI."
    )
    options: List[str] = Field(
        ...,
        description="A list of clear, concise, and distinct options for the user to choose from."
    )

class QuestionRouter(BaseModel):
    """
    The router for determining which questions to ask the user based on their initial idea.
    It MUST generate between 3 to 5 questions.
    """
    questions: List[Question] = Field(
        ...,
        description="A list of 3 to 5 dynamically generated questions to ask the user."
    )
